language: c

compiler:
  - gcc
  - clang

before_script:
  - echo 'yes' | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install dh-make

script:
  - make all
  - make tests
  - echo | dh_make --copyright bsd --email andre@florath.net --single --addmissing --packagename libdontdie_1.0 --createorig
  - dpkg-buildpackage
  